### ISSUE TITLE
All size | Symbol(&) shows instead of text

### ISSUE THREAD

**Issue by Shahnul-sebpo** [sebpo1/USCS_2851#1]
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Presidents_Day_Sale_tr_CANE_feed

![image](https://github.com/sebpo1/USCS_2851/assets/95062434/1042d932-047a-4f5a-a700-da8b53a23721)

**Comment by mitaly-sebpo** [comment]
call out
