### ISSUE TITLE
all size| basefile| version name  mismatched 

### ISSUE THREAD

**Issue by retuparna-sebpo** [sebpo1/USCS_2851#12]
version name should be NE Europe as per ticket description

![image](https://github.com/sebpo1/USCS_2851/assets/106819920/55a695fc-01a9-4469-b50c-0ea82c72c7c3)

**Comment by kaziragib-sebpo** [comment]
[Updated_feedversion_failsafe.xlsx](https://github.com/sebpo1/USCS_2851/files/14518142/Updated_feedversion_failsafe.xlsx)

**Comment by bikash-sebpo** [comment]
Solved.
![image](https://github.com/sebpo1/USCS_2851/assets/95098369/ea29be29-ebc3-49e4-9b58-267c8e81fd91)
