### ISSUE TITLE
160x60 | All browser(M) | Line break mismatch with windows browser

### ISSUE THREAD

**Issue by Shahnul-sebpo** [sebpo1/USCS_2851#15]
All version

![image](https://github.com/sebpo1/USCS_2851/assets/95062434/7746e8d9-dcfc-430c-842b-a92c9bb53d15)

**Comment by mitaly-sebpo** [comment]
fixed

**Comment by Shahnul-sebpo** [comment]
160x600 - ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_CANE_non_feed
300x600 - ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_Med_non_feed

**Comment by mitaly-sebpo** [comment]
fixed for 300x600
