### ISSUE TITLE
300x250 | all browsers| frame 1|  incorrect headline alignment

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#17]
extra space before headline text in windows browsers
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_Alaska_non_feed

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/61802228-a69f-4210-ac89-fe214ffc27d3)

in mac safari less space
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_Alaska_feed
![image](https://github.com/sebpo1/USCS_2851/assets/142499806/2aac92f6-8685-4735-aaa2-d3da31c3f081)

**Comment by nahid-sebpo** [comment]
fixed

**Comment by nahid-sebpo** [comment]
Before  giving any issues, we should refer to our previously approved version as a reference like  "  presidentday " sale campain. We should ignore these issues based on the existing approved version.
