### ISSUE TITLE
300x250, 728x90 | all browser | text overlap

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#18]
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_Med_feed

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/8bed8482-42b0-4193-8524-4f38cbca6266)

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/530c0f73-ae10-4848-90eb-7d66afdbb736)

**Comment by fariha-sebpo** [comment]
Solved.
