### ISSUE TITLE
300x600 | all browser | line height inconsistency comparing to other version and text overlapping

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#19]
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_NEurope_non_feed

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/aa9334d5-08b4-45a5-b3b0-e4d27e5f6c87)

**Comment by fariha-sebpo** [comment]
Solved.
![image](https://github.com/sebpo1/USCS_2851/assets/109519777/c50f3a6b-113c-4c21-bc66-bb7932ee5383)
