### ISSUE TITLE
160x600 | all browser | text is very near to border

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#21]
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_Caribbean_feed
default_MemorialDaySale_Caribbean

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/3350b809-69d5-4c52-85dd-90ec4530d8a7)

**Comment by AbiirHossen09** [comment]
Half Fixed

**Comment by nahid-sebpo** [comment]
these version are fixed
default_MemorialDaySale_Caribbean

**Comment by Zeba-SEBPO** [comment]
solved

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/3b7dace2-ff46-4f91-95a8-87fb81902ef9)
