### ISSUE TITLE
300x600 | all browser | text is almost overlapped with border

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#22]
for all browser -
default_MemorialDaySale_CANE 
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_CANE_feed

Only for FF (all)
 ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_Caribbean_non_feed

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/6ad98731-0a97-4210-b46a-a99fe2558e50)

ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_Caribbean_non_feed
![image](https://github.com/sebpo1/USCS_2851/assets/142499806/e7d4571b-ea8b-44d7-856e-cd9b0a1c4deb)

**Comment by AbiirHossen09** [comment]
Half fixed

**Comment by AbiirHossen09** [comment]
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_CANE_feed

Only for FF (all)
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_Caribbean_non_feed

**Comment by nahid-sebpo** [comment]
these version are fixed

default_MemorialDaySale_CANE

**Comment by Zeba-SEBPO** [comment]
solved
![image](https://github.com/sebpo1/USCS_2851/assets/142499806/42548d1e-d28e-4801-9997-6e51ffb9b87b)
