### ISSUE TITLE
970x250 | FF(all), Safari | browser wise line break inconsistent

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#24]
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_Crossings_non_feed

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/64cd3dcf-5471-47e5-bf89-da85e35c9f67)

**Comment by fariha-sebpo** [comment]
Solved.
![image](https://github.com/sebpo1/USCS_2851/assets/109519777/ff2ab885-1555-4528-b017-ce30c7103283)
