### ISSUE TITLE
300x250 | mac ( Safari) |text is overlapping with logo image and very near to border

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#25]
overlapping with logo image 
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_CANE_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_Crossings_feed

very near to border
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_CANE_non_feed

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/f83ddfd9-5ecf-4512-b8b8-b8c8f404e9f3)

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/a1096595-55ce-4607-9b1d-0ab7f79f35ca)

**Comment by fariha-sebpo** [comment]
Solved.
![image](https://github.com/sebpo1/USCS_2851/assets/109519777/9e8399e3-3836-4cb0-a521-f1baaad5e49d)
