### ISSUE TITLE
970x250| ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_Med_feed| “Voyages” should be in the same line as “Mediterranean”

### ISSUE THREAD

**Issue by rifa-sebpo** [sebpo1/USCS_2851#26]
![Snag_7d67770f](https://github.com/sebpo1/USCS_2851/assets/95363731/1918b245-b521-4185-a9dc-740ec7c8e16b)
![Snag_7d68e843](https://github.com/sebpo1/USCS_2851/assets/95363731/f5c73470-7e9f-410e-af42-6d4bae7fd270)

**Comment by anwar-sebpo** [comment]
Fixed
![image](https://github.com/sebpo1/USCS_2851/assets/95041175/f753ce88-acd0-4bd9-ad6d-7d4280156f89)

**Comment by saadat-sebpo** [comment]
Resolved 
![image](https://github.com/sebpo1/USCS_2851/assets/95076892/f9e04b16-070f-480d-804e-ab85dcdcffd4)
