### ISSUE TITLE
970x250 | k-weight exceeds to 300KB

### ISSUE THREAD

**Issue by fariha-sebpo** [sebpo1/USCS_2851#29]
![image](https://github.com/sebpo1/USCS_2851/assets/109519777/49b8c4fa-542b-4241-8883-5b37e845948d)
**ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_Alaska_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_CANE_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_CANE_non_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_Crossings_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_Crossings_non_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_Med_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_Med_non_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_NEurope_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_NEurope_non_feed**

**Comment by nahid-sebpo** [comment]
fixed

**Comment by mithila-sebpo** [comment]
solved
![image](https://github.com/sebpo1/USCS_2851/assets/95068780/53e3f341-57d2-40d8-ad1c-b9cf7d5c5805)
