### ISSUE TITLE
970x250 | all browser | frame2,4 | letters are very near to each other comparing to other frames

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#30]
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_CANE_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_Alaska_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_Med_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_NEurope_feed

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/009e4a71-b056-457d-95f4-be0b0e2f9627)

**Comment by nahid-sebpo** [comment]
Please ignore these issues, as the feed endpoint data is showing from the 2nd frame onward.

**Comment by mithila-sebpo** [comment]
Issue closed as ignored as per the Dev's comment
