### ISSUE TITLE
970x250 | FF (all), Safari | last frame | widow word

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#31]
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_Crossings_non_feed

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/340a1af8-dd38-4844-89de-2f546259177d)

**Comment by nahid-sebpo** [comment]
fixed

**Comment by saudbinshahid** [comment]
not fixed for safari

**Comment by saudbinshahid** [comment]
<img width="1009" alt="Image20240522020310" src="https://github.com/sebpo1/USCS_2851/assets/156332652/fb1cc5bf-fb04-4852-b1cc-d229490aaa39">
