### ISSUE TITLE
970x250 | FF (all), Safari | frame 2 | line break mismatch 

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#32]
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_CANE_non_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Upgrades_on_us_tr_Crossings_feed 

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/0afce2f9-d7aa-439b-aa54-77555e15946e)

**Comment by nahid-sebpo** [comment]
fixed

**Comment by saudbinshahid** [comment]
Not fixed for safari

**Comment by saudbinshahid** [comment]
<img width="1035" alt="Image20240522020314" src="https://github.com/sebpo1/USCS_2851/assets/156332652/51517742-e080-4c57-9287-4f66f8440ec4">
