### ISSUE TITLE
all size | all browser | ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Queen_Anne_Offer_Default_feed | according to feedback this default version should have only one static frame but it has 2 frames

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#33]
![image](https://github.com/sebpo1/USCS_2851/assets/142499806/f3f22321-68d7-4621-8f37-968951b63374)

**Comment by nahid-sebpo** [comment]
![image](https://github.com/sebpo1/USCS_2851/assets/95094891/286d500a-a297-42d5-8f83-1040dbc95b7e)
![image](https://github.com/sebpo1/USCS_2851/assets/95094891/2864f874-e194-458b-b5ec-17538c7b6bae)
