### ISSUE TITLE
970x250 | MAC browsers| Text is centered between logo and CTA 

### ISSUE THREAD

**Issue by kiron-sebpo** [sebpo1/USCS_2851#35]
Version Name: 

ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Queen_Anne_Offer_feed_tr_Caribbean_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Queen_Anne_Offer_tr_Alaska_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Queen_Anne_Offer_tr_CANE_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Queen_Anne_Offer_tr_Crossings_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Queen_Anne_Offer_tr_Med_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Queen_Anne_Offer_tr_NEurope_feed

**Comment by kaziragib-sebpo** [comment]
please check if it is centered on chrome

**Comment by kiron-sebpo** [comment]
Solved
