### ISSUE TITLE
Basefile: All sizes: IMCS & RTG_Non-Feed : F3 bg image name mismatch with matrix.

### ISSUE THREAD

**Issue by bikash-sebpo** [sebpo1/USCS_2851#36]
### Version name: ad_Cunard_cy_FY24_fp_IMCS_af_DYM_Display_Banner_pt_Promo_ac_Independence_Day_Sale_tr_Med_non_feed

![Snag_94ff4c9](https://github.com/sebpo1/USCS_2851/assets/95098369/787df3eb-b95e-40c5-aa83-5ad02a4ee8a2)

**Comment by mitaly-sebpo** [comment]
Please check the image visually .Name will not be matched
