### ISSUE TITLE
Basefile: RTG: Matrix dnt have feedend point but basefile have.

### ISSUE THREAD

**Issue by bikash-sebpo** [sebpo1/USCS_2851#38]
![image](https://github.com/sebpo1/USCS_2851/assets/95098369/8dd15c46-9bed-4695-9bd3-ee5fcc8ebd7a)

**Comment by mitaly-sebpo** [comment]
![image](https://github.com/sebpo1/USCS_2851/assets/106811834/c5497005-cee9-44e3-a413-b0a073ee1ae6)
Matrix have feed end point
