### ISSUE TITLE
Basefile: RTG: Feed: Wrong image there in all frames.

### ISSUE THREAD

**Issue by bikash-sebpo** [sebpo1/USCS_2851#39]
![Snag_34fa8f](https://github.com/sebpo1/USCS_2851/assets/95098369/bb2aab53-f6df-47d2-8068-f764884ab5db)

**Comment by mitaly-sebpo** [comment]
![image](https://github.com/sebpo1/USCS_2851/assets/106811834/03820727-a15b-4fe8-ba34-b732f4731a9f)
![image](https://github.com/sebpo1/USCS_2851/assets/106811834/a48d3a98-dca7-4018-b1f7-4ce80c781b45)

**Comment by mitaly-sebpo** [comment]
All the image name is same , we added memorial at the end of assets name

**Comment by bikash-sebpo** [comment]
I was wrong.
