### ISSUE TITLE
300x600 | RTG | Mac(Safari),W(FF) | Frame-1 | Headline text is overlaping with logo

### ISSUE THREAD

**Issue by saudbinshahid** [sebpo1/USCS_2851#40]
Version Name: ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Independence_Day_Sale_tr_Caribbean_feed
Version Name: ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Independence_Day_Sale_tr_Med_feed
Version Name: ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Independence_Day_Sale_tr_NEurope_feed

![Snag_3e93b10](https://github.com/sebpo1/USCS_2851/assets/156332652/c14f9516-48d9-4db0-8769-cbaced649299)

**Comment by nahid-sebpo** [comment]
fixed

**Comment by saudbinshahid** [comment]
![Snag_40ae44f](https://github.com/sebpo1/USCS_2851/assets/156332652/3ee6bbce-1f1f-492b-a27a-b28416e69a86)
