### ISSUE TITLE
970x250 | all browser | Static-  RTG , IMCS | IDS_Static_627630 , IDS_Static_71710 | content missing

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#41]
![image](https://github.com/sebpo1/USCS_2851/assets/142499806/04892324-c8b6-4cd1-94de-749982b2e3cc)

**Comment by nahid-sebpo** [comment]
fixed

**Comment by Zeba-SEBPO** [comment]
solved

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/58466b8c-233d-40ba-975c-de804032c7d4)
