### ISSUE TITLE
300x600, 970x250 | file size exceed

### ISSUE THREAD

**Issue by Zeba-SEBPO** [sebpo1/USCS_2851#43]
CUN_2024_RTG_Dynamic_300x600.zip
CUN_2024_RTG_Dynamic_970x250.zip

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/f2ed3d7b-ed0d-4e54-aff3-faf65e672e68)

**Comment by nahid-sebpo** [comment]
fixed

**Comment by Zeba-SEBPO** [comment]
solved

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/1acb611d-f2ef-4607-8763-b7285406530d)
