### ISSUE TITLE
300x600 | Frame 1 | ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_NEurope_feed | "Northen Europe Voyages" text is not center between the copy

### ISSUE THREAD

**Issue by kiron-sebpo** [sebpo1/USCS_2851#44]
Version Name: 

![image](https://github.com/sebpo1/USCS_2851/assets/95046195/e516aa5f-5990-49d9-8591-f7bb58e8bdde)

**Comment by nahid-sebpo** [comment]
@kiron-sebpo bhai, @Israq-sebpo bhai
This is an invalid issue.  The issue you mentioned is related to the Memorial Day campaign, but we are currently working on the Independence Day campaign, so this is not relevant.

**Comment by Zeba-SEBPO** [comment]
according to developer's comment we are closing this issue
