### ISSUE TITLE
ALL size except 970x250 |chrome (w) | Last frame is not match with 970x250 sizes

### ISSUE THREAD

**Issue by kiron-sebpo** [sebpo1/USCS_2851#45]
Version Name: ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Memorial_Day_Sale_tr_Crossings_feed
![image](https://github.com/sebpo1/USCS_2851/assets/95046195/4ec74bc7-3b0b-4b62-9449-321acad83e12)

**Comment by nahid-sebpo** [comment]
This is an invalid issue. Based on client feedback, we don't see any problems on our side. The issue you mentioned is related to the Memorial Day campaign, but we are currently working on the Independence Day campaign, so this is not relevant.
