### ISSUE TITLE
728*90 | All Browsers(W,M) | Alaska RTG Feed & Non-Feed | Headline (IDS)  font weight inconsistent in each browsers

### ISSUE THREAD

**Issue by Kongkon-sebpo** [sebpo1/USCS_2851#46]
![Snag_5f9d66d](https://github.com/sebpo1/USCS_2851/assets/142218761/ddb63fbb-1f48-4bc5-9355-c8ea156a6106)
![Snag_5fb4fee](https://github.com/sebpo1/USCS_2851/assets/142218761/6f9b5b6e-9167-45d3-be17-2044d016da6c)

**Comment by nahid-sebpo** [comment]
We do not see any font weight inconsistency related issue on our side. Please ignore it. 
If needed, you can refer to the previously approved campaign versions for reference. Thanks.
