### ISSUE TITLE
300x600 | All Browsers (W,M) | Europe RTG Feed | 'Northern Europe Voyages' is not centered

### ISSUE THREAD

**Issue by Kongkon-sebpo** [sebpo1/USCS_2851#47]
![image](https://github.com/sebpo1/USCS_2851/assets/142218761/72ef6b24-6706-4ff1-bc49-b3461e9ab4f3)

**Comment by nahid-sebpo** [comment]
fixed

**Comment by Zeba-SEBPO** [comment]
solved

![image](https://github.com/sebpo1/USCS_2851/assets/142499806/ebca811d-c080-4538-b616-df259e937c3a)
