### ISSUE TITLE
728x90 | RTG | all bowser | ad doesn't load

### ISSUE THREAD

**Issue by mithila-sebpo** [sebpo1/USCS_2851#48]
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Presidents_Day_Sale_tr_Crossings_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Presidents_Day_Sale_tr_CANE_feed
![image](https://github.com/sebpo1/USCS_2851/assets/95068780/0e55e5ec-8ab3-4c54-b32d-e403a00c8ad9)

**Comment by saddam-sebpo** [comment]
The client shared feedback for Big Balcony versions, these two are Presidents Day Sale versions. Thank you
![image](https://github.com/sebpo1/USCS_2851/assets/95040515/8ca41e03-426c-48b9-abab-5c9ed956a51a)

**Comment by mithila-sebpo** [comment]
Issue closed as ignored as per the Dev's comment
