### ISSUE TITLE
300x600,160x600 | Non feed | Register trade mark position mismatch with ref

### ISSUE THREAD

**Issue by Shahnul-sebpo** [sebpo1/USCS_2851#7]
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Treat_yourself_on_us_tr_Crossings_non_feed

![image](https://github.com/sebpo1/USCS_2851/assets/95062434/b7460aa4-fde4-40cd-8681-1b394550e1dd)

**Comment by mitaly-sebpo** [comment]
[Non-feed.xlsx](https://github.com/sebpo1/USCS_2851/files/14429419/Non-feed.xlsx)
