### ISSUE TITLE
728x90 | Non feed | F2 & F3 image mismatch with ref

### ISSUE THREAD

**Issue by Shahnul-sebpo** [sebpo1/USCS_2851#8]
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Treat_yourself_on_us_tr_Alaska_non_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Treat_yourself_on_us_tr_CANE_non_feed
ad_Cunard_cy_FY24_fp_RTG_af_DYM_Display_Banner_pt_Promo_ac_Treat_yourself_on_us_tr_NEurope_non_feed

![image](https://github.com/sebpo1/USCS_2851/assets/95062434/0609a655-9cdf-490e-97ef-e80cd0d99436)

**Comment by kaziragib-sebpo** [comment]
[versions-export_All_size.xlsx](https://github.com/sebpo1/USCS_2851/files/14429447/versions-export_All_size.xlsx)
updated basefile
