### ISSUE TITLE
728x90, 300x600,160x600 | All browser(W,M) | All version(non feed) | Register trade mark overlap

### ISSUE THREAD

**Issue by Shahnul-sebpo** [sebpo1/USCS_2851#9]
![image](https://github.com/sebpo1/USCS_2851/assets/95062434/f671e551-9f22-4d23-9c05-237d02e8626d)

![image](https://github.com/sebpo1/USCS_2851/assets/95062434/689d6046-26f7-4176-8f85-366781364eea)

**Comment by kaziragib-sebpo** [comment]
Fixed for 728x90

**Comment by Shahnul-sebpo** [comment]
![image](https://github.com/sebpo1/USCS_2851/assets/95062434/a0e2091a-5ec3-4247-96d0-b453a9c4f8ca)
